#!/bin/bash
## https://docs.docker.com/docker-hub/builds/advanced/

## GIT_BRANCH equals both invoking branch or tag.
## Strip of a release suffix
docker build \
  --build-arg RELEASE=${GIT_BRANCH%-r*} \
  -t $IMAGE_NAME .
